Vp/min 158 pool creation
minterest-finance/minterest-chain-node pull request #115
Opened 2021-05-14 14:04 UTC by dev-vadim

**Description:**

Describe in brief, what was done.

**Changes in storage or API:**

Describe storage structure changes or API changes. Make sure to update the [API docs](https://minterestfinance.atlassian.net/wiki/spaces/MINTEREST/pages/134807557/Minterest+API).

**Checklist**

- [ ] Code is covered with tests
- [ ] Code is covered with benchmarks
- [ ] Fresh benchmark results included

2021-05-17 10:35 UTC, lut1k commented on pallets/minterest-protocol/src/lib.rs
> +			Self::do_create_pool(
pull*

2021-05-20 10:06 UTC, kurotych commented on pallets/integration-tests/src/tests/mnt_token_tests.rs
> +				vec![DOT, ETH].into_iter().for_each(|pool_id| {
Is it necessary to have admin participate as user in mnt calculation?

2021-05-20 10:06 UTC, kurotych commented on pallets/integration-tests/src/tests/mnt_token_tests.rs
> +				assert_eq!(Currencies::free_balance(MNT, &ALICE), 2_989_130_353_325_167_984);
To make sure that alice accepted rewards from BTC pool
```suggestion
				assert_ok!(MinterestProtocol::claim_mnt(alice(), vec![DOT, ETH]));
				assert_eq!(Currencies::free_balance(MNT, &ALICE), 2858695574289277984);
				assert_ok!(MinterestProtocol::claim_mnt(alice(), vec![BTC]));
				assert_eq!(Currencies::free_balance(MNT, &ALICE), 2989130353325167984);
			})

```

2021-05-20 11:38 UTC, Apollo50 commented
Do not forget to update types.json

2021-05-20 13:30 UTC, kurotych requested changes

2021-05-20 13:30 UTC, kurotych commented on pallets/liquidity-pools/src/lib.rs
> +		Pools::<T>::insert(
As this function public, I suggest to add additional check is pool exists.To prevent rewriting

2021-05-20 13:30 UTC, kurotych commented on pallets/liquidity-pools/src/tests.rs
> +		.pool_mock(ETH)
Seems useless (user_balance also)

2021-05-20 13:30 UTC, kurotych commented on pallets/liquidity-pools/src/tests.rs
> +		.pool_mock(BTC)
Seems useless

2021-05-20 13:30 UTC, kurotych commented on pallets/minterest-model/src/lib.rs
> +	pub fn create_pool(
As this function public, I suggest to add additional check is pool exists.To prevent rewriting

2021-05-20 13:30 UTC, kurotych commented on pallets/minterest-protocol/src/tests.rs
> +		.pool_with_params(ETH, Balance::zero(), Rate::one(), Balance::zero())
It seems useless

2021-05-20 13:30 UTC, kurotych commented on pallets/minterest-protocol/src/tests.rs
> +		.pool_with_params(ETH, Balance::zero(), Rate::one(), Balance::zero())
It seems useless

2021-05-20 13:30 UTC, kurotych commented on pallets/minterest-protocol/src/tests.rs
> +		.pool_with_params(ETH, Balance::zero(), Rate::one(), Balance::zero())
It seems useless

2021-05-20 13:30 UTC, kurotych commented on pallets/minterest-protocol/src/tests.rs
> +		.pool_with_params(ETH, Balance::zero(), Rate::one(), Balance::zero())
It seems useless

2021-05-20 13:30 UTC, kurotych commented on pallets/minterest-protocol/src/tests.rs
> +		.pool_with_params(ETH, Balance::zero(), Rate::one(), Balance::zero())
It seems useless. And so on, I am tired)

2021-05-20 13:30 UTC, kurotych commented on pallets/mnt-token/src/lib.rs
> +		type LiquidityPoolsManager: LiquidityPoolsManager + PoolsManager<Self::AccountId>;
We can add this definition to traits
pub trait LiquidityPoolsManager<Self::AccountId> : PoolsManager<Self::AccountId>

2021-05-20 13:30 UTC, kurotych commented on pallets/risk-manager/src/lib.rs
> +			);
Is it code duplication?

2021-05-20 13:30 UTC, kurotych commented on pallets/risk-manager/src/lib.rs
> +					|| !RiskManagerParams::<T>::contains_key(underlying_id)
Is it possible to add pool to risk_manager in `create_pool` extrinsic to avoid such situations?

2021-05-20 13:30 UTC, kurotych commented on pallets/traits/src/lib.rs
> +	fn create_pool(currency_id: CurrencyId, deviation_threshold: Rate, balance_ratio: Rate);
Add description

2021-05-20 13:30 UTC, kurotych commented on pallets/traits/src/lib.rs
> +	fn create_pool(
Add description

2021-05-20 14:14 UTC, dev-vadim commented on pallets/controller/src/lib.rs
> +
After we added new CurrencyId but haven`t executed create_pool() new CurrencyId is recognized as supported underlying asset, so we need to add pool_exists() check

2021-05-20 14:18 UTC, kurotych commented on pallets/controller/src/lib.rs
> +
But why `T::LiquidityPoolsManager::pool_exists(&pool_id)` isn't enough? Why do we need check is_supported_underlying_asset previously?

2021-05-20 15:37 UTC, dev-vadim commented on pallets/minterest-protocol/src/lib.rs
> +		ensure!(
Done

2021-05-20 15:39 UTC, dev-vadim commented on pallets/controller/src/lib.rs
> +
pool_exists goes to storage, so in my opinion it`s good to check validity of the CurrencyId first and only after that check storage

2021-05-20 15:39 UTC, dev-vadim commented on pallets/integration-tests/src/tests/controller_tests.rs
> +			.pool_initial(ETH)
That was a copy&paste. Removed.

2021-05-20 15:39 UTC, dev-vadim commented on pallets/integration-tests/src/tests/controller_tests.rs
> +			.pool_initial(ETH)
Removed

2021-05-20 15:39 UTC, dev-vadim commented on pallets/integration-tests/src/tests/liquidity_pools_tests.rs
> +			.pool_initial(ETH)
Removed

2021-05-20 15:39 UTC, dev-vadim commented on pallets/integration-tests/src/tests/liquidity_pools_tests.rs
> +			.pool_initial(ETH)
Removed

2021-05-20 15:39 UTC, dev-vadim commented on pallets/integration-tests/src/tests/liquidity_pools_tests.rs
> +			.pool_initial(ETH)
Removed

2021-05-20 15:39 UTC, dev-vadim commented on pallets/integration-tests/src/tests/minterest_model_tests.rs
> +			.pool_initial(ETH)
Removed

2021-05-20 15:39 UTC, dev-vadim commented on pallets/integration-tests/src/tests/minterest_model_tests.rs
> +			.pool_initial(ETH)
Removed

2021-05-20 15:40 UTC, dev-vadim commented on pallets/integration-tests/src/tests/minterest_protocol_tests.rs
> +			.pool_initial(ETH)
Removed

2021-05-20 15:40 UTC, dev-vadim commented on pallets/integration-tests/src/tests/minterest_protocol_tests.rs
> +			.pool_initial(ETH)
Removed

2021-05-20 15:40 UTC, dev-vadim commented on pallets/integration-tests/src/tests/minterest_protocol_tests.rs
> +			.pool_initial(ETH)
Removed

2021-05-20 15:40 UTC, dev-vadim commented on pallets/integration-tests/src/tests/minterest_protocol_tests.rs
> +			.pool_initial(ETH)
Removed

2021-05-20 15:40 UTC, dev-vadim commented on pallets/integration-tests/src/tests/mnt_token_tests.rs
> +				// Alice шы able to claim rewards from all three pools
Sorry, Russian isn`t my mother tongue)

2021-05-20 15:41 UTC, dev-vadim commented on pallets/integration-tests/src/tests/mnt_token_tests.rs
> +				vec![DOT, ETH].into_iter().for_each(|pool_id| {
Changed admin -> bob

2021-05-20 15:42 UTC, dev-vadim commented on pallets/integration-tests/src/tests/mnt_token_tests.rs
> +				assert_eq!(Currencies::free_balance(MNT, &ALICE), 2_989_130_353_325_167_984);
Done

2021-05-20 15:42 UTC, dev-vadim commented on pallets/integration-tests/src/tests/scenario_tests.rs
> +			.pool_initial(ETH)
Removed.

2021-05-20 15:42 UTC, dev-vadim commented on pallets/liquidity-pools/src/tests.rs
> +		.pool_mock(ETH)
Removed.

2021-05-20 15:42 UTC, dev-vadim commented on pallets/liquidity-pools/src/tests.rs
> +		.pool_mock(BTC)
Removed.

2021-05-20 15:42 UTC, dev-vadim commented on pallets/minterest-protocol/src/tests.rs
> +		.pool_with_params(ETH, Balance::zero(), Rate::one(), Balance::zero())
Removed.

2021-05-20 15:43 UTC, dev-vadim commented on pallets/minterest-protocol/src/tests.rs
> +		.pool_with_params(ETH, Balance::zero(), Rate::one(), Balance::zero())
Removed.

2021-05-20 15:43 UTC, dev-vadim commented on pallets/minterest-protocol/src/tests.rs
> +		.pool_with_params(ETH, Balance::zero(), Rate::one(), Balance::zero())
Removed.

2021-05-20 15:43 UTC, dev-vadim commented on pallets/minterest-protocol/src/tests.rs
> +		.pool_with_params(ETH, Balance::zero(), Rate::one(), Balance::zero())
Removed.

2021-05-20 15:43 UTC, dev-vadim commented on pallets/risk-manager/src/lib.rs
> +			);
Copy&paste mistake. Switched the second check to RiskManagerParams check

2021-05-20 15:49 UTC, Apollo50 commented on pallets/integration-tests/src/tests/mnt_token_tests.rs
> +	fn test_mnt_token_scenario_n_2() {
why do we need this test in general ?
It repeats parts of logic in test scenario_n_1, we want to check if it works correctly after adding new pool, but we don't check if expected value and real match.

2021-05-20 16:30 UTC, Apollo50 reviewed
What do you think about add possibility to don't set all params at the same time.
We can use orml_trait Change:
**pub enum Change`<`Value`>` {
   /// No change.
   NoChange,
   /// Changed to new value.
   NewValue(Value),
}**

**pub fn example(
   origin: OriginFor<T>,
   currency_id: CurrencyId,
   rate: ChangeOptionRate,
   ratio: ChangeOptionRatio,
   balance: ChangeBalance,
) -> DispatchResultWithPostInfo**

That allows us to remove all single setters.

2021-05-20 16:30 UTC, Apollo50 commented on pallets/controller/src/lib.rs
> +			},
I've discussed with Denis. We need unpause all operations when we calling this function :rofl: 
But in default, all should be paused.

2021-05-21 08:20 UTC, lut1k commented
liquidity-pools/srs/lib.rs
`pub fn get_exchange_rate(underlying_asset: CurrencyId) -> RateResult {...}`
In my opinion, the semantics of this function is broken. In the case when we do not have a pool, it returns a rating equal to one. In my opinion, this function should return an error in this case.
I think it is necessary to add a check `ensure!(Self::pool_exists(&underlying_asset), Error::<T>::PoolNotFound);` to this function and, accordingly, remove the same checks from the 'upper' functions that call this one.

2021-05-21 08:26 UTC, lut1k commented
This is not your request, but could you return the scripts folder?) It was deleted by mistake.
https://github.com/minterest-finance/minterest-chain-node/blob/4173ae8187ac721c673437465c799b0be3d3e2ee/scripts/init.sh

2021-05-21 08:40 UTC, lut1k commented
This is a comment on your previous PR. But, in my opinion, this needs to be fixed now.
liquidity-pools/src/lib.rs
function:
```pub fn get_exchange_rate_by_interest_params(
		underlying_asset: CurrencyId,
		total_protocol_interest: Balance,
		total_borrowed: Balance,
	) -> RateResult { ... }
```
not covered by unit tests.
In this function, just like in the function `fn get_exchange_rate()` is necessary to check `pool_exists()`. And if the pool doesn't exists return an `Err`.

2021-05-21 08:48 UTC, lut1k commented
At the moment, when adding a new currency to the protocol, we have problems connecting the frontend part to the node.
The frontend calls RPC for a specific currency (for example, a RPC api.rpc.controller.liquidityPoolState) and it returns a `Non` for the newly added currency. And the frontend at the moment does not handle this situation, and the page goes into endless loading.
Probably, it is necessary that the newly added currency on the frontend is not active, but the entire page is loaded correctly.
In my opinion, it is necessary to do joint work with front-end developers. And merge your branch to the master only after the frontend part has been changed.

Also, when you describe the Flow in the Confluence, do not forget to mention that you need to add the oracle_price for a given currency in order for the protocol to start working correctly.

2021-05-21 09:57 UTC, lut1k commented on pallets/liquidation-pools/src/lib.rs
> +
```suggestion
			ensure!(
				T::LiquidityPoolsManager::pool_exists(&supply_pool_id)
					&& T::LiquidityPoolsManager::pool_exists(&target_pool_id),
				Error::<T>::PoolNotFound
			);
```
This suggestion is optional :)

2021-05-21 09:57 UTC, lut1k commented on pallets/minterest-protocol/src/lib.rs
> +			);
This error is raised only here in the minterest-protocol pallet. Why would we declare these errors on the liquidity-pool pallet and liquidation-pools pallet? I think it is better to declare this error in the minterest-protocol pallet.
We also do not have tests for this check. I think it is worth covering this check with tests.

2021-05-21 16:09 UTC, dev-vadim commented on pallets/liquidation-pools/src/lib.rs
> +				deviation_threshold: deviation_threshold,
Done

2021-05-21 16:09 UTC, dev-vadim commented on pallets/controller/src/lib.rs
> +				max_borrow_rate: max_borrow_rate,
Done

2021-05-21 16:09 UTC, dev-vadim commented on pallets/minterest-model/src/lib.rs
> +				kink: kink,
Done

2021-05-21 16:20 UTC, dev-vadim commented on pallets/mnt-token/src/lib.rs
> +		type LiquidityPoolsManager: LiquidityPoolsManager + PoolsManager<Self::AccountId>;
As far as I understand it is implemented in other branch and will be merged soon. If so I`ll wait for it to be merged and pull the changes into my branch)

2021-05-21 16:21 UTC, dev-vadim commented on pallets/traits/src/lib.rs
> +	fn create_pool(currency_id: CurrencyId, deviation_threshold: Rate, balance_ratio: Rate);
Done

2021-05-21 16:21 UTC, dev-vadim commented on pallets/traits/src/lib.rs
> +	fn create_pool(
Done

2021-05-21 17:08 UTC, dev-vadim commented on pallets/minterest-protocol/src/tests.rs
> +				},
Done

2021-05-21 17:08 UTC, dev-vadim commented on pallets/minterest-protocol/src/lib.rs
> +			);
Done

2021-05-21 17:08 UTC, dev-vadim commented on pallets/liquidation-pools/src/lib.rs
> +
Done

2021-05-21 17:09 UTC, dev-vadim commented on pallets/risk-manager/src/lib.rs
> +					|| !RiskManagerParams::<T>::contains_key(underlying_id)
Done

2021-05-21 17:09 UTC, dev-vadim commented on pallets/controller/src/lib.rs
> +			},
Done

2021-05-24 17:16 UTC, dev-vadim commented on pallets/liquidity-pools/src/lib.rs
> +		Pools::<T>::insert(
Done

2021-05-24 17:17 UTC, dev-vadim commented on pallets/integration-tests/src/tests/mnt_token_tests.rs
> +	fn test_mnt_token_scenario_n_2() {
Left the test as is to have an additional check that MNT distribution won`t break when new pool is added

2021-05-24 19:12 UTC, lut1k commented
types.json:
```
"TokenSymbol": {
      "_enum": {
        "MNT": 0,
        "DOT": 1,
        "MDOT": 2,
        "KSM": 3,
        "MKSM": 4,
        "BTC": 5,
        "MBTC": 6,
        "ETH": 7,
        "METH": 8,
        "TMP": 9,
         "MTMP": 10
      }
```
Add TMP and MTMP or remove them from rust code.

2021-05-25 06:41 UTC, lut1k commented on pallets/controller/src/lib.rs
> +		}
This check is unnecessary, it has already been done in the method `fn get_exchange_rate()`.

2021-05-25 06:41 UTC, lut1k commented on pallets/minterest-protocol/src/lib.rs
> +			pool_data: Box<PoolInitData>,
Can ypu describe the reason, why we are using a smart pointer to heap here?

2021-05-25 06:41 UTC, lut1k commented on pallets/minterest-protocol/src/lib.rs
> +		pub fn create_pool(
Can add explanatory comments. Who can call this extrinsic and why.

2021-05-25 06:41 UTC, lut1k commented on pallets/traits/src/lib.rs
> +	fn create_pool(
Not done :)
And this comment applies to all methods in all pallets. Please, add a description to all methods `fn create_pool()` in all pallets.

2021-05-25 06:41 UTC, lut1k commented on pallets/minterest-protocol/src/lib.rs
> +type MinterestModel<T> = minterest_model::Module<T>;
I think its' better to add functionality from the pallet minterest-model using the `trait`. Just as it is already done for the pallet risk-manager.

2021-05-25 08:31 UTC, dev-vadim commented on pallets/minterest-protocol/src/lib.rs
> +			pool_data: Box<PoolInitData>,
If I remember correctly it was clippy who had complained for such big structure. The reason is that Call is enum and will take as much space in memory as the biggest variant, so instead of having big structure as parameter it suggested to have a pointer to heap

2021-05-25 11:26 UTC, dev-vadim commented on pallets/controller/src/lib.rs
> +		}
Removed

2021-05-25 11:26 UTC, dev-vadim commented on pallets/minterest-protocol/src/lib.rs
> +			pool_data: Box<PoolInitData>,
Removed Box and added exception for clippy

2021-05-25 11:26 UTC, dev-vadim commented on pallets/minterest-protocol/src/lib.rs
> +		pub fn create_pool(
Done

2021-05-25 11:27 UTC, dev-vadim commented on pallets/minterest-protocol/src/lib.rs
> +type MinterestModel<T> = minterest_model::Module<T>;
Done

2021-05-25 11:27 UTC, dev-vadim commented on pallets/controller/src/lib.rs
> +		PauseKeepers::<T>::insert(
Done

2021-05-25 11:34 UTC, lut1k submitted a review, later dismissed

2021-05-26 10:30 UTC, dev-vadim commented on pallets/integration-tests/src/tests/mnt_token_tests.rs
> +	fn test_mnt_token_scenario_n_2() {
Added one more test as asked above. @kurotych please check

2021-05-26 11:40 UTC, lut1k approved these changes

2021-05-26 11:50 UTC, kurotych commented on pallets/traits/src/lib.rs
> +	fn create_pool(
Agree. Add description please

2021-05-26 11:50 UTC, kurotych commented on pallets/integration-tests/src/tests/mnt_token_tests.rs
> +	fn test_mnt_token_scenario_n_2() {
LGTM

2021-05-26 14:06 UTC, kurotych commented on runtime/src/lib.rs
> +		fn pool_exists(underlying_asset_id: CurrencyId) -> Option<bool> {
Pool is exists or not. 
Do we actually need Option here?

2021-05-26 14:09 UTC, lut1k commented on runtime/src/lib.rs
> +		fn pool_exists(underlying_asset_id: CurrencyId) -> Option<bool> {
RPC always should return `Option`. Otherwise, may be panic. yep?

2021-05-26 14:42 UTC, dev-vadim commented on pallets/controller/rpc/runtime-api/src/lib.rs
> +pub struct PoolExists {
Removed

2021-05-26 14:42 UTC, dev-vadim commented on pallets/controller/rpc/src/lib.rs
> +	) -> Result<Option<bool>> {
Fixed

2021-05-26 14:42 UTC, dev-vadim commented on pallets/liquidity-pools/src/tests.rs
> +			// exchange_rate = (100 - 0 + 0) / 125 = 0.8
Done

2021-05-26 14:42 UTC, dev-vadim commented on pallets/minterest-protocol/src/tests.rs
> +						liquidation_fee: Rate::saturating_from_rational(105, 100),
Done

2021-05-26 14:42 UTC, dev-vadim commented on pallets/minterest-protocol/src/tests.rs
> +		.user_balance(ALICE, MKSM, ONE_HUNDRED_DOLLARS)
Done

2021-05-26 14:43 UTC, dev-vadim commented on pallets/risk-manager/src/lib.rs
> +		PoolAlreadyCreated1,
Fixed

2021-05-26 14:43 UTC, dev-vadim commented on runtime/src/lib.rs
> +		fn pool_exists(underlying_asset_id: CurrencyId) -> Option<bool> {
Fixed

2021-05-26 15:01 UTC, lut1k approved these changes

2021-05-26 15:20 UTC, Apollo50 approved these changes

2021-05-27 06:31 UTC, kurotych approved these changes
Poehali

2021-05-27 06:35 UTC, merged